# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83abb92b6ee744b9e0af0a945f33b9eb6ed6a31469abff0cf32039109fcd268020dcedc4f67df606de98e9666531a6c79dba3d2339a1180cc2d0b95987b33141

test:
  secret_key_base: 46df1cedb652e0ac7fbed5c337549e4c98d5e6845843379223d5a92ca3f0708d553ec913e651b6918fc5457564c5f829a6d5ccfd119872167c3ce117ed4d8afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
